Sc 3287/tableau download view as file
shipyardapp/tableau-blueprints pull request #2
Opened 2022-05-18 17:15 UTC by hughsons

download view from tableau server

2022-05-18 18:17 UTC, ericelsken requested changes

2022-05-18 18:17 UTC, ericelsken commented on tableau_blueprints/download_view.py
> +    server, tableau_auth = authenticate_tableau(username, password, site_id, server_url)
I like the `authenticate_tableau` function, and it looks like it's being used for making sure we can authenticate and exit with a specific error code if not. But, then in the other functions you are passing in `server`, `tableau_auth` and then calling `server.auth.sign_in(tableau_auth)` multiple times in a `with` clause. 
Is that a requirement of the way the sdk works - I'm guessing not? 

Can you instead do the authentication once? You could call `authenticate_tableau` and have that function return the context to use in `with`, or call `with server.auth.sign_in(tableau_auth)` once in main, and pass just `server.views` to the other functions that need it. 
This all reduces the number of parameters needed in each function, and forces authentication to a single point. 

**This also applies to the `refresh_datasource.py` file.**

2022-05-18 22:02 UTC, blakeburch requested changes
High level things to add:

1) User needs the ability to create the file in a specified subdirectory. If this value isn't provided, it should be created in cwd (what you currently have the code doing). See other Blueprint examples to see how we typically handle this.
2) This needs to handle for overlapping view names. A view name is required to be unique in Tableau per workbook, so I think the workbook also needs to be specified. Currently it just chooses one and moves forward.
3) Same comment as on refresh_datasource.py. Is there a response we can get access to and store?

2022-05-18 22:02 UTC, blakeburch commented on tableau_blueprints/download_view.py
> +    parser.add_argument('--site_id', dest='site_id', required=True)
Argument should use `-` as separator

2022-05-18 22:02 UTC, blakeburch commented on tableau_blueprints/download_view.py
> +                server.views.populate_pdf(views, req_options=None)
The populate_pdf function is used here, instead of I assume `populate_csv` resulting in `tableauserverclient.models.exceptions.UnpopulatedPropertyError: View item must be populated with its csv first.`

2022-05-18 22:02 UTC, blakeburch commented on tableau_blueprints/download_view.py
> +                server.views.populate_pdf(views, req_options=None)
Same issue here with populate_pdf, resulting in resulting in `tableauserverclient.models.exceptions.UnpopulatedPropertyError: View item must be populated with its csv first.`

2022-05-18 22:02 UTC, blakeburch commented on tableau_blueprints/download_view.py
> +        sys.exit(EXIT_CODE_INVALID_RESOURCE)
Same comment as `refresh_datasource.py`. I think we should be checking to see if an ID was found in the function that looks it up rather than after the fact.

2022-05-18 22:02 UTC, blakeburch commented on tableau_blueprints/download_view.py
> +        sys.exit(EXIT_CODE_INVALID_RESOURCE)
This error wouldn't be INVALID_RESOURCE. It would be a new error related to file writing.

2022-05-18 22:02 UTC, blakeburch commented on tableau_blueprints/download_view.py
> +
If we're not using 211 and 212, remove them

2022-05-18 22:02 UTC, blakeburch commented on tableau_blueprints/download_view.py
> +                    f.write(b''.join(views.csv))
Could be lack of knowledge on my side. Any reason why this one has to be written with the byte join and the others don't?

2022-05-18 22:02 UTC, blakeburch commented on tableau_blueprints/download_view.py
> +            print("View saved to current directory successfully")
Let's make the success message specific.

View {view_name} successfully saved to {file_path}.

2022-05-20 01:31 UTC, hughsons commented on tableau_blueprints/download_view.py
> +                    f.write(b''.join(views.csv))
as per the docs i have used it.

2022-06-09 02:52 UTC, closed without merging